- name: copy ssh identities
  copy:
    src: /Users/kvaradhan/.ssh/id_ed25519-vm
    dest: /root/.ssh/id_ed25519
    mode: 0600
    directory_mode: 0700
- copy:
    src: /Users/kvaradhan/.ssh/id_ed25519-vm.pub
    dest: /root/.ssh/id_ed25519.pub
    mode: 0600
    directory_mode: 0700

- name: copy nscacert.pem
  copy:
    src:  /Library/Application Support/Netskope/STAgent/data/nscacert.pem
    dest: /etc/ssl/certs/nscacert.pem

- name: update ca certs
  command: /usr/sbin/update-ca-certificates --fresh
